server:
  port: 8080

spring:
  application:
    name: devops-training

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.devopstraining: INFO